name: Saludo usando variables y secretos
on:
  workflow_dispatch
env:
  SALUDO: Hola
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      DIA_DE_SEMANA : Lunes
    steps:
      - name: Saludo variables
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Hoy es $DIA_DE_SEMANA"
  saludo-secretos:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo secretos
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Tu contraseña es ${{ secrets.CONTRASENA }}!"
